name: gambit_cli
description: A sample command-line application.
version: 1.3.3
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  dartz: ^0.10.1
  dcli: ^5.0.0
  dio: ^5.5.0+1
  firebaseapis: ^0.2.0
  freezed_annotation: ^2.4.4
  googleapis_auth: ^1.6.0
  jose: ^0.3.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
